name: Deploy Static Website Code

on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Replace with your desired AWS region

      - name: Run AWS CLI Command
        run: |
          # Your AWS CLI command here
          aws s3 ls
          # aws s3 cp temp s3://kaveri-static-website --recursive

      - name: Run Linux Commands 
        run: |
          pwd
          ls
          
      - name: Notify on success
        if: success()
        run: echo "Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: echo "Deployment failed!"
